### ISSUE TITLE
liri networkmanager module does not seem to build with Qt 5.14

### ISSUE THREAD

**Issue by n3rdopolis** [lirios/networkmanager#4]
It seems I get this build error with building against Qt 5.14 even after attempting to add a `#include <QMapIterator>` to `src/imports/networkmanager/connectionsettings.cpp`

```
[ 89%] Building CXX object src/imports/networkmanager/CMakeFiles/nmplugin.dir/networkmodelitem.cpp.o
In file included from /opt/include/KF5/NetworkManagerQt/networkmanagerqt/settings.h:29,
                 from /opt/include/KF5/NetworkManagerQt/NetworkManagerQt/Settings:1,
                 from /srcbuild/lirios-networkmanager/src/imports/networkmanager/connectionsettings.cpp:24:
/opt/include/KF5/NetworkManagerQt/networkmanagerqt/generictypes.h:44:9: error: ‘QMapIterator’ does not name a type; did you mean ‘operator+’?
 typedef QMapIterator<QString, QString> NMStringMapIterator;
         ^~~~~~~~~~~~
         operator+

```

**Comment by n3rdopolis** [comment]
Got it to build by commenting out `QT_NO_JAVA_STYLE_ITERATORS` in `https://github.com/lirios/cmake-shared/blob/develop/modules/LiriAddQmlPlugin.cmake`
